Models/ErrorViewModel.cs
namespace TestTask.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Folder.cs
using System.ComponentModel.DataAnnotations;

namespace TestTask.Models
{
    public class Folder
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [Range(1, 20)]
        public string Name { get; set; }
        public int? ParentFolderId { get; set; }
    }
}

Controllers/FoldersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using TestTask.Data;
using TestTask.Models;

namespace TestTask.Controllers
{
    public class FoldersController : Controller
    {
        private readonly FolderDbContext _db;

        public FoldersController(FolderDbContext db) {  _db = db; }

        public IActionResult Index(int? id = null)
        {
            var childCatalogs = _db.Folders.Where(c => c.ParentFolderId == id).ToList();
            if (childCatalogs == null)
            {
                return NotFound();
            }

            var parentFolder = _db.Folders.FirstOrDefault(c => c.Id == id);
            if (id != null)
            {
                ViewBag.ParentFolderName = parentFolder.Name;
            }
            else
            {
                ViewBag.ParentFolderName = null;
            }
            
            return View(childCatalogs);
        }
        [HttpGet]
        public IActionResult ExportToFile()
        {
            var folders = _db.Folders.ToList(); // Отримання всіх папок з бази даних

            // Серіалізація в JSON
            var json = JsonConvert.SerializeObject(folders, Formatting.Indented);

            // Отримання фізичного шляху до папки Files
            var filesFolderPath = Path.Combine(Directory.GetCurrentDirectory(), "Files");

            // Перевірка існування папки Files
            if (!Directory.Exists(filesFolderPath))
            {
                Directory.CreateDirectory(filesFolderPath); // Створення папки, якщо вона не існує
            }

            // Шлях до файлу JSON у папці Files
            var filePath = Path.Combine(filesFolderPath, "folders.json");

            // Запис у файл JSON у папці Files
            System.IO.File.WriteAllText(filePath, json);

            // Повернення повідомлення користувачеві
            return Content("Structure exported to file");
        }

        [HttpPost]
        public async Task<IActionResult> ImportFromFile(IFormFile file)
        {
            if (file == null || file.Length == 0)
                return Content("file not selected");

            _db.Folders.RemoveRange(_db.Folders); 

            string jsonContent;
            using (var reader = new StreamReader(file.OpenReadStream()))
            {
                jsonContent = await reader.ReadToEndAsync();
            }

            var folders = JsonConvert.DeserializeObject<List<Folder>>(jsonContent);

            _db.Folders.AddRange(folders);
            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
        
        [HttpGet]
        public IActionResult ImportAndExportOfFiles()
        {
            return View();
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TestTask.Models;

namespace TestTask.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Folders/ImportAndExportOfFiles.cshtml
@{
    ViewData["Title"] = "ImportAndExportOfFiles";
}

<a asp-controller="Folders" asp-action="ExportToFile" class="my-a">Export Structure</a>
<form method="post" enctype="multipart/form-data" asp-controller="Folders" asp-action="ImportFromFile" class="import-form">
    <input type="file" name="file" class="my-input" />
    <input type="submit" value="Import" class="my-button" />
</form>

Views/Folders/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

@model List<Folder>

<div>
    @if (@ViewBag.ParentFolderName != null)
    {
        <h1>"Folder": @ViewBag.ParentFolderName</h1>
    }
    else{
        <a asp-controller="Folders" asp-action="ImportAndExportOfFiles" class="my-a">Import/Export</a>
    }
    <div class="folders">
        @foreach (var folder in Model)
        {
            <div class="folder">
                <a asp-controller="Folders" asp-action="Index" asp-route-id="@folder.Id" class="folder">
                    <img src="~/img/folder.png" class="folder-img" />
                    @folder.Name
                </a>

            </div>
        }
    </div>
    
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TestTask</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/foldersStyles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TestTask.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TestTask</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Folders" asp-action="Index">Folders</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - TestTask - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>